{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-manager-webhook-freemyip.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "cert-manager-webhook-freemyip.labels" . | indent 4 }}
type: Opaque
data:
  token: {{ .Values.freemyip.token | b64enc }}
{{- end }}
